### PR TITLE
moving PR to new dev branch, see #71 & #74 for more details

### PR DESCRIPTION
**Pull request by derjungeinhd**
see #71 & #74 for more details

### CODE REVIEW

**Comment by derjungeinhd** [comment]
@WasabiThumb before merging, I forgot to exclude my changes for the Chat Messages. I accidentally skipped the part that you are hesistant about that. I will leave this PR open in case you decide to make that change. Close it or tell me if you decide overwise, I'll open another PR with this time only the other changes...

**Comment by WasabiThumb** [comment]
The issue seems to be fixed on the `dev/1.12.1` branch, so the changes that print the prompt to chat will no longer be necessary. Feel free to make another PR with _just_ the translation & 404 updates, or reply to #76 if you are still having issues after the changes. I would merge the correct changes myself but that would deprive you of the contributor badge ;) Afterwards 1.12.1 can be released. Thanks <3

**Comment by derjungeinhd** [comment]
@WasabiThumb I finally got the right branch with the right changes, see #79. Sorry for the chaos, I'm really bad with using git.... I had no problems with the prompts anymore since the newest 1.12.1 dev build.
But I'm a little bit concerned about the use of the action bar since many servers use it for a timer or something like that. I'm working on a solution to activate the chat notifications via the config, but I won't make another PR, since I don't want to force you to implement it after this PR flood.

**Comment by WasabiThumb** [comment]
> @WasabiThumb I finally got the right branch with the right changes, see #79. Sorry for the chaos, I'm really bad with using git.... I had no problems with the prompts anymore since the newest 1.12.1 dev build. But I'm a little bit concerned about the use of the action bar since many servers use it for a timer or something like that. I'm working on a solution to activate the chat notifications via the config, but I won't make another PR, since I don't want to force you to implement it after this PR flood.

That's a fine idea, just make sure that your implementation doesn't cause unparsed MiniMessage tags to show up in either the chat, action bar or boss bar.

**Comment by derjungeinhd** [comment]
I managed to make it optional, here if you want to take a look at it: https://github.com/derjungeinhd/xclaim/pull/4/commits/09fd25c7d5c350c2ed0225060a8157266759abcd

**Comment by WasabiThumb** [comment]
That looks fine. I will remember this if it turns out to be an issue, but the action bar is updated by this plugin every tick so collision with other plugins also using the action bar is unlikely. I specifically didn't use the chat because chat on large servers can be quite ferocious and I also don't want to spam empty messages to wipe it off screen.

**Pull request closed without merging**
